[package]
name = "toolbelt"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1"
axum = "0.8"
clap = { version = "4.5", features = ["derive"] }
composable-runtime = { git = "https://github.com/modulewise/composable-runtime", tag = "v0.2.0", default-features = false }
rmcp = { version = "0.12", features = ["server", "transport-streamable-http-server", "transport-worker"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
